### ISSUE TITLE
IPv4 is down

### ISSUE THREAD

**Issue by danielprashaanth** [arapurayil/dns#2]
Dear Arapurayil,

I am from India and I am happy you provide a service like this in India, I am trying to configure your IPv4 on my router to provide a ad free network to my family members but unfortunately your server for 51.15.66.89 is down.

But I can confirm, DoH and DoT are working completely fine. Can you kindly check the issue with the above IP as it benefit everyone.

Thank you, expecting a solution soon.

**Comment by arapurayil** [comment]
Hi! You must use DoH/DoT/dnscrypt if you would like to use my server. The server is intended to work over encrypted protocols only and not plain DNS. The IPv4 address is provided for hostname resolution only.
Unfortunately only few routers support these protocols natively. Asus routers support DoT, but otherwise you probably would have to flash OpenWrt firmware to use DoH/DoT/dnscrypt.
If you're stuck with plain DNS I suggest you checkout NextDNS. They're pretty good and have servers in India - Pune I think.

**Comment by danielprashaanth** [comment]
> 
> 
> Hi! You must use DoH/DoT/dnscrypt if you would like to use my server. The server is intended to work over encrypted protocols only and not plain DNS. The IPv4 address is provided for hostname resolution only.
> Unfortunately only few routers support these protocols natively. Asus routers support DoT, but otherwise you probably would have to flash OpenWrt firmware to use DoH/DoT/dnscrypt.
> If you're stuck with plain DNS I suggest you checkout NextDNS. They're pretty good and have servers in India - Pune I think.

Thank you so much for the reply and suggestion for NextDNS and ASUS Routers, appreciate it.
